[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sibr-module"
version = "0.1.9"
authors = [
    { name="Sigvard Bratlie", email="sigvard@sibr.no" },
]
description = "Help modules for different applications, especially for google cloud"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "LICENSE" }
keywords = ["google cloud", "bigquery", "gcs", "utilities"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ['bigframes',
 'db-dtypes',
 'gcsfs',
 'google-api-core',
 'google-auth',
 'google-auth-oauthlib',
 'google-cloud',
 'google-cloud-appengine-logging',
 'google-cloud-audit-log',
 'google-cloud-bigquery',
 'google-cloud-bigquery-connection',
 'google-cloud-bigquery-storage',
 'google-cloud-core',
 'google-cloud-functions',
 'google-cloud-iam',
 'google-cloud-logging',
 'google-cloud-resource-manager',
 'google-cloud-storage',
 'google-cloud-secret-manager',
 'google-crc32c',
 'grpcio',
 'numpy',
 'pandas',
 'pandas-gbq',
 'pyarrow',
 'joblib',
 'PyYaml',
 'openpyxl',
]

[project.urls]
"Homepage" = "https://github.com/sigvardbratlie/sibr-module"
"Bug Tracker" = "https://github.com/sigvardbratlie/sibr-module/issues"